apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql-deployment # Pegar em matchLabels no arquivo de deployment em que se quer referenciar o service que será criado
  ports:
  - port: 3306
    #targetPort: 8080 não vamos utilizar, pois, utilizaremos a padrão
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
  - port: 80